# Generated by Django 2.1.8 on 2019-07-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.DateField(verbose_name='date published')),
                ('space', models.CharField(max_length=200)),
                ('purchase_link', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('detail_map', models.CharField(max_length=200)),
                ('precautions', models.TextField()),
                ('notice', models.TextField()),
                ('poster', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
            options={
                'ordering': ['schedule'],
            },
        ),
        migrations.CreateModel(
            name='RegisterNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='festa',
            name='number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_festa.RegisterNum'),
        ),
    ]
