# Generated by Django 2.2.3 on 2019-08-02 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='schedule_end',
            field=models.DateField(default=datetime.date(2019, 8, 2), verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festa',
            name='schedule_start',
            field=models.DateField(default=datetime.date(2019, 8, 1), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
