# Generated by Django 2.2.3 on 2019-08-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0002_auto_20190802_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festa',
            options={'ordering': ['schedule_start']},
        ),
        migrations.RemoveField(
            model_name='festa',
            name='schedule',
        ),
    ]
