# Generated by Django 2.2.3 on 2019-07-19 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0002_auto_20190717_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festa',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='festa',
            name='image',
        ),
        migrations.RemoveField(
            model_name='festa',
            name='info',
        ),
        migrations.AddField(
            model_name='festa',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festa',
            name='host',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festa',
            name='notice',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festa',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festa',
            name='precautions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='festa',
            name='purchase_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
