# Generated by Django 2.2.3 on 2019-08-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0003_auto_20190803_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festa',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
