# Generated by Django 2.2.3 on 2019-08-06 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0004_auto_20190806_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festa',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
