# Generated by Django 2.1.8 on 2019-07-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0006_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('password', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=200)),
                ('writer2', models.CharField(max_length=100)),
                ('pub_date2', models.DateTimeField(verbose_name='date published')),
                ('password2', models.CharField(max_length=20)),
                ('body2', models.TextField()),
            ],
        ),
    ]
