# Generated by Django 2.1.8 on 2019-07-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0007_now_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festa',
            options={'ordering': ['schedule']},
        ),
    ]
