# Generated by Django 2.2.3 on 2019-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0007_now_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='festa',
            options={'ordering': ['schedule']},
        ),
    ]
