# Generated by Django 2.2.3 on 2019-07-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0009_auto_20190726_0225'),
        ('app_festa', '0009_commentn_commentt_home'),
    ]

    operations = [
    ]
