# Generated by Django 2.1.8 on 2019-07-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0010_merge_20190727_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_home', models.CharField(max_length=200)),
                ('content_home', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Home')),
            ],
        ),
    ]
