# Generated by Django 2.2.3 on 2019-07-27 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0010_merge_20190727_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompany',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Commenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_accompany', models.CharField(max_length=200)),
                ('content_accompany', models.TextField()),
                ('accompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Accompany')),
            ],
        ),
    ]
