# Generated by Django 2.2.3 on 2019-07-27 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0011_auto_20190727_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
