# Generated by Django 2.2.3 on 2019-07-27 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0012_ticket_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenttic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_ticket', models.CharField(max_length=200)),
                ('content_ticket', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Ticket')),
            ],
        ),
    ]
