# Generated by Django 2.2.3 on 2019-07-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0013_commenttic'),
        ('app_festa', '0011_commenth'),
    ]

    operations = [
    ]
