# Generated by Django 2.2.3 on 2019-07-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0015_festa_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenta',
            name='accompany',
        ),
        migrations.RemoveField(
            model_name='commenth',
            name='home',
        ),
        migrations.RemoveField(
            model_name='commentn',
            name='now',
        ),
        migrations.RemoveField(
            model_name='commentt',
            name='team',
        ),
        migrations.RemoveField(
            model_name='commenttic',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Accompany',
        ),
        migrations.DeleteModel(
            name='Commenta',
        ),
        migrations.DeleteModel(
            name='Commenth',
        ),
        migrations.DeleteModel(
            name='Commentn',
        ),
        migrations.DeleteModel(
            name='Commentt',
        ),
        migrations.DeleteModel(
            name='Commenttic',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Now',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
