# Generated by Django 2.2.3 on 2019-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0016_auto_20190728_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='detail_map',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
