# Generated by Django 2.1.8 on 2019-08-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_festa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_home', models.CharField(max_length=200)),
                ('content_home', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentlf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_lost_found', models.CharField(max_length=200)),
                ('content_lost_found', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_now', models.CharField(max_length=200)),
                ('content_now', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_team', models.CharField(max_length=200)),
                ('content_team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('강원', '강원'), ('충남', '충남'), ('충북', '충북'), ('경북', '경북'), ('경남', '경남'), ('전북', '전북'), ('전남', '전남'), ('제주', '제주')], max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
        migrations.CreateModel(
            name='Lost_Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('post_type', models.CharField(choices=[('분실', '분실'), ('습득', '습득')], max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
        migrations.CreateModel(
            name='Now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('post_type', models.CharField(choices=[('now', 'now'), ('질문', '질문'), ('나눔', '나눔')], max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('password', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=30)),
                ('reservation_num', models.CharField(max_length=30)),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=200)),
                ('writer2', models.CharField(max_length=100)),
                ('post_type', models.CharField(choices=[('공지사항', '공지사항'), ('긴급공지', '긴급공지'), ('질문', '질문')], max_length=100)),
                ('pub_date2', models.DateTimeField(verbose_name='date published')),
                ('password2', models.CharField(max_length=20)),
                ('body2', models.TextField()),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
        migrations.AddField(
            model_name='commentt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festaNow.Team'),
        ),
        migrations.AddField(
            model_name='commentn',
            name='now',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festaNow.Now'),
        ),
        migrations.AddField(
            model_name='commentlf',
            name='lost_found',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festaNow.Lost_Found'),
        ),
        migrations.AddField(
            model_name='commenth',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festaNow.Home'),
        ),
    ]
