# Generated by Django 2.2.3 on 2019-08-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0001_initial'),
        ('app_festaNow', '0002_remove_reservationnum_festa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationnum',
            name='festa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa'),
            preserve_default=False,
        ),
    ]
