# Generated by Django 2.2.3 on 2019-08-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaNow', '0005_auto_20190804_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='post_type',
        ),
    ]
