# Generated by Django 2.2.3 on 2019-08-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaNow', '0006_remove_team_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='post_type',
            field=models.CharField(choices=[('중요', '중요'), ('질문', '질문')], default='중요', max_length=100),
            preserve_default=False,
        ),
    ]
