# Generated by Django 2.2.3 on 2019-08-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaNow', '0009_lost_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentlf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_lost_found', models.CharField(max_length=200)),
                ('content_lost_found', models.TextField()),
                ('Lost_Found', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festaNow.Lost_Found')),
            ],
        ),
    ]
