# Generated by Django 2.2.4 on 2019-08-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaNow', '0010_commentlf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlf',
            old_name='Lost_Found',
            new_name='lost_found',
        ),
        migrations.AlterField(
            model_name='home',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('강원', '강원'), ('충남', '충남'), ('충북', '충북'), ('경북', '경북'), ('경남', '경남'), ('전북', '전북'), ('전남', '전남'), ('제주', '제주')], max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_type',
            field=models.CharField(choices=[('공지사항', '공지사항'), ('긴급공지', '긴급공지'), ('질문', '질문')], max_length=100),
        ),
    ]
