# Generated by Django 2.2.3 on 2019-08-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_festa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('강원', '강원'), ('충남', '충남'), ('충북', '충북'), ('경북', '경북'), ('경남', '경남'), ('전북', '전북'), ('전남', '전남'), ('제주', '제주')], max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deal_type', models.CharField(choices=[('양도해요', '양도해요'), ('양도받아요', '양도받아요'), ('교환해요', '교환해요')], max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
        migrations.CreateModel(
            name='Commenttic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festaReady.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Commenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festaReady.Accompany')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa')),
            ],
        ),
    ]
