# Generated by Django 2.2.3 on 2019-08-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_festa', '0001_initial'),
        ('app_festaReady', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenta',
            name='festa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_festa.Festa'),
            preserve_default=False,
        ),
    ]
