# Generated by Django 2.2.3 on 2019-07-29 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompany',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
