# Generated by Django 2.2.3 on 2019-08-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompany',
            name='area',
            field=models.CharField(choices=[('서울', '서울'), ('제주', '제주'), ('경기', '경기')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deal_type',
            field=models.CharField(choices=[('양도해요', 'give_trnsf'), ('양도받아요', 'get_trnsf'), ('교환', 'exchange')], max_length=200),
        ),
    ]
