# Generated by Django 2.2.4 on 2019-08-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0002_auto_20190804_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompany',
            name='area',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('강원', '강원'), ('충남', '충남'), ('충북', '충북'), ('경북', '경북'), ('경남', '경남'), ('전북', '전북'), ('전남', '전남'), ('제주', '제주')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deal_type',
            field=models.CharField(choices=[('양도해요', '양도해요'), ('양도받아요', '양도받아요'), ('교환해요', '교환해요')], max_length=200),
        ),
    ]
