# Generated by Django 2.2.3 on 2019-08-08 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0002_commenta_festa'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commenta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
