# Generated by Django 2.2.3 on 2019-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0002_auto_20190730_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompany',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
