# Generated by Django 2.2.3 on 2019-07-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0003_auto_20190730_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
