# Generated by Django 2.2.3 on 2019-08-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0003_auto_20190808_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenta',
            old_name='content_accompany',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='commenta',
            old_name='writer_accompany',
            new_name='writer',
        ),
    ]
