# Generated by Django 2.2.3 on 2019-08-02 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_festaReady', '0004_auto_20190730_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenta',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commenttic',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
